### PR TITLE
R2python

### PR DESCRIPTION
**Pull request by danielrazavi**
Changes made in an effort to move the course from a R class to a Python class.
- Changed the structure of the course:
  - Word Documents (assignments) -> Markdown Files (assignments)
  - R files -> Python Files
- Changed the slides and lesson plans to reflect changing the course's programming language from R to Python.
- Included the needed data (`mammalsleep.csv`) for the `DSI-Sampling-Multiple Imputation Exerises.py` file.
- Updated the .gitignore file to ignore data files created by the `5.1-Probability-LLN Demo.py` script and any related vscode files.

### CODE REVIEW

**Comment by mandyyao98** [comment]
The hyperlinks in the lesson plans don't work for me anymore, could this be double checked please?

**Comment by danielrazavi** [comment]
> The hyperlinks in the lesson plans don't work for me anymore, could this be double checked please?

this used to work for you before the update I made today?

**Comment by mandyyao98** [comment]
Yes, it worked before the update.

**Comment by danielrazavi** [comment]
> Yes, it worked before the update.

@mandyyao98 For the time being, if you can just take a look at the lecture folder for the files, that would be really appreciated. As this is a low priority feature, I will push it back in the backlog and address it later on during the course.

**Comment by danielrazavi** [comment]
@morrisgreenberg @mandyyao98 It would be great if I can get an approval by today so that we can merge in the changes before the beginning of the class.

**Comment by morrisgreenberg** [comment]
Hi Daniel,

I would suggest committing the changes, and then updating the hyperlinks to
be the urls to the relevant materials rather than the relative path. Once
that is done, I would fully approve (but it would require committing the
updates that you've already done in the interim).

Morris

**Review by mandyyao98 — APPROVED** [review]

**Comment by danielrazavi** [comment]
Per conversations with Mandy and Morris, in the next PR, I will be updating the hyperlinks.

**Pull request merged**
